from django.urls import path

from .views import (
    LanguageListView,
    CourseListView,
    CourseMapView,
    LessonDetailView,
    SubmitExerciseAnswerView,
    CompleteLessonView,
    MyLearningProfileView,
    MyMistakesView,
    CourseSelectView,
    PlacementTestView,
    PlacementSubmitView,
    VocabularyListView,
    GrammarRuleListView,
    RecommendedLearningMethodView,
    NextLessonView,
    RuleTutorHintView,
    MyWordReviewView,
    SelectCompanionView,
    MyCompanionView,
    CompanionListView,
    ClaimDailyTaskView,
    MyDailyTasksView,
    MarkAchievementsSeenView,
    MyAchievementsView,
    ParentChildrenListView,
    ChildOverviewView,
    ChildActivityView,
    ChildMistakesView,
    ChildWordsView,
    ChildWeeklySummaryView,
    TopicListView,
    MyInterestsView,
    MyChallengesView,
)

urlpatterns = [
    path("languages/", LanguageListView.as_view()),
    path("courses/", CourseListView.as_view()),
    path("courses/<int:course_id>/map/", CourseMapView.as_view()),
    path("lessons/<int:lesson_id>/", LessonDetailView.as_view()),
    path("exercises/<int:exercise_id>/answer/", SubmitExerciseAnswerView.as_view()),
    path("lessons/<int:lesson_id>/complete/", CompleteLessonView.as_view()),
    path("me/profile/", MyLearningProfileView.as_view()),
    path("me/mistakes/", MyMistakesView.as_view()),
    path("courses/select/", CourseSelectView.as_view()),
    path("placement/<int:course_id>/", PlacementTestView.as_view()),
    path("placement/submit/", PlacementSubmitView.as_view()),
    path("vocabulary/", VocabularyListView.as_view()),
    path("grammar-rules/", GrammarRuleListView.as_view()),
    path("me/recommended-method/", RecommendedLearningMethodView.as_view()),
    path("me/next-lesson/", NextLessonView.as_view()),
    path("tutor/hint/", RuleTutorHintView.as_view()),
    path("me/word-review/", MyWordReviewView.as_view()),
    path("me/achievements/", MyAchievementsView.as_view(), name="my-achievements"),
    path("me/achievements/seen/", MarkAchievementsSeenView.as_view(), name="achievements-seen"),
    # Daily tasks
    path("me/daily-tasks/", MyDailyTasksView.as_view(), name="my-daily-tasks"),
    path("daily-tasks/<int:task_id>/claim/", ClaimDailyTaskView.as_view(), name="claim-daily-task"),
    # Companion
    path("companions/", CompanionListView.as_view(), name="companion-list"),
    path("me/companion/", MyCompanionView.as_view(), name="my-companion"),
    path("companion/select/", SelectCompanionView.as_view(), name="select-companion"),
    
    path("children/", ParentChildrenListView.as_view(), name="children-list"),
    path("children/<int:profile_id>/overview/", ChildOverviewView.as_view(), name="child-overview"),
    path("children/<int:profile_id>/activity/", ChildActivityView.as_view(), name="child-activity"),
    path("children/<int:profile_id>/mistakes/", ChildMistakesView.as_view(), name="child-mistakes"),
    path("children/<int:profile_id>/words/", ChildWordsView.as_view(), name="child-words"),
    path("children/<int:profile_id>/weekly-summary/", ChildWeeklySummaryView.as_view(), name="child-weekly-summary"),
    
    path("topics/", TopicListView.as_view()),
    path("me/interests/", MyInterestsView.as_view()),
    path("me/challenges/", MyChallengesView.as_view()),
]