# Generated by Django 5.2.14 on 2026-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
