# Generated by Django 5.2.14 on 2026-05-20 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairingcode',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_pairing_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='child_status',
            field=models.CharField(choices=[('active', 'Active'), ('non_active', 'Non active')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
