# Generated by Django 5.2.14 on 2026-05-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='device_id',
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='first_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'device_id'], name='parent_devi_user_id_0b72e7_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='parent_devi_user_id_45806e_idx'),
        ),
    ]
