# Generated by Django 5.2.14 on 2026-06-01 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_gamecategory_shopcategory_remove_savedlocation_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildInstalledApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=150)),
                ('package_name', models.CharField(max_length=255)),
                ('app_icon', models.ImageField(blank=True, null=True, upload_to='child_apps/icons/')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_system_app', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['app_name'],
                'unique_together': {('child', 'package_name')},
            },
        ),
        migrations.CreateModel(
            name='ChildBlockedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_apps', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_blocks', to=settings.AUTH_USER_MODEL)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='parent.childinstalledapp')),
            ],
        ),
        migrations.CreateModel(
            name='ChildAppLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit_seconds', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_limits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_limits', to=settings.AUTH_USER_MODEL)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limit', to='parent.childinstalledapp')),
            ],
        ),
        migrations.CreateModel(
            name='ChildAppControlEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('limit_created', 'Limit created'), ('limit_updated', 'Limit updated'), ('limit_removed', 'Limit removed'), ('app_blocked', 'App blocked'), ('app_unblocked', 'App unblocked')], max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_app_control_events', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_control_events', to=settings.AUTH_USER_MODEL)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_events', to='parent.childinstalledapp')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildAppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('total_usage_seconds', models.PositiveIntegerField(default=0)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usages', to=settings.AUTH_USER_MODEL)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='parent.childinstalledapp')),
            ],
            options={
                'ordering': ['-usage_date', '-total_usage_seconds'],
                'unique_together': {('child', 'app', 'usage_date')},
            },
        ),
    ]
