# Generated by Django 5.2.14 on 2026-06-01 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0005_childinstalledapp_childblockedapp_childapplimit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childinstalledapp',
            name='app_icon',
        ),
        migrations.AlterField(
            model_name='childapplimit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_child_app_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='childblockedapp',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_child_app_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChildAppControlEvent',
        ),
    ]
