# Generated by Django 5.2.14 on 2026-06-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0006_remove_childinstalledapp_app_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childlocation',
            options={'ordering': ['created_at']},
        ),
    ]
