# Generated by Django 5.2.14 on 2026-06-05 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0010_subscriptionplan_usersubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenterTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('waiting', 'Kutilmoqda'), ('resolved', 'Hal qilingan'), ('closed', 'Yopilgan'), ('blocked', 'Bloklangan')], default='new', max_length=30)),
                ('title', models.CharField(default='Foydalanuvchi murojaati', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_tickets', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_center_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CallCenterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('old_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_center_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='parent.callcenterticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
