# Generated by Django 5.2.14 on 2026-06-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0016_parentnotification_sos_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentnotification',
            name='category',
            field=models.CharField(choices=[('zone_in', 'Zone in'), ('zone_out', 'Zone out'), ('zone_transition', 'Zone transition'), ('destination', 'Destination'), ('battery', 'Battery'), ('offline', 'Offline'), ('login', 'Login'), ('order', 'Order'), ('shipping', 'Shipping'), ('deal', 'Deal'), ('screen', 'Screen time'), ('premium', 'Premium'), ('tip', 'Tip'), ('route', 'Route'), ('place_recommendation', 'Place recommendation'), ('system', 'System'), ('sos', 'SOS')], default='system', max_length=32),
        ),
        migrations.AlterField(
            model_name='parentstoreproduct',
            name='age_label',
            field=models.CharField(blank=True, default='', help_text='Masalan 6+ yosh', max_length=40),
        ),
        migrations.AlterField(
            model_name='parentstoreproduct',
            name='category_label',
            field=models.CharField(blank=True, default='', help_text='Kartochkada chiqadigan kichik label, masalan STEM O‘YINCHOQ', max_length=120),
        ),
    ]
