# Generated by Django 5.2.14 on 2026-06-09 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0017_alter_parentnotification_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Admin uchun yorliq', max_length=180)),
                ('trigger_type', models.CharField(choices=[('premium_expiry', 'Premium tugashidan oldin'), ('daily', 'Har kuni'), ('weekly', 'Har hafta'), ('monthly', 'Har oy'), ('one_off', 'Bir martalik')], default='one_off', max_length=30)),
                ('trigger_params', models.JSONField(blank=True, default=dict)),
                ('audience', models.CharField(choices=[('all_parents', 'Hamma ota-onalar'), ('premium_active', 'Premium aktiv'), ('premium_expiring', 'Premium tugashga yaqin'), ('free_users', 'Bepul foydalanuvchilar'), ('no_active_child', 'Bolasi ulanmagan')], default='all_parents', max_length=30)),
                ('audience_params', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(default='system', max_length=40)),
                ('send_push', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_active', 'next_run_at'], name='parent_noti_is_acti_fa9d02_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('push_sent', models.PositiveIntegerField(default=0)),
                ('sms_sent', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('detail', models.TextField(blank=True, default='')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='parent.notificationrule')),
            ],
            options={
                'ordering': ['-fired_at'],
            },
        ),
    ]
