# Generated by Django 5.2.14 on 2026-06-10 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0021_i18n_roles_areablock'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcentercomment',
            name='direction',
            field=models.CharField(choices=[('in', 'Kiruvchi'), ('out', 'Chiquvchi')], default='out', max_length=4),
        ),
        migrations.AddField(
            model_name='callcentercomment',
            name='telegram_message_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='callcenterticket',
            name='source',
            field=models.CharField(choices=[('app', 'Ilova'), ('telegram', 'Telegram'), ('manual', "Qo'lda")], default='app', max_length=20),
        ),
        migrations.AddField(
            model_name='callcenterticket',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='callcenterticket',
            name='telegram_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='callcenterticket',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='parentstoreproduct',
            name='category_label_en',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='parentstoreproduct',
            name='category_label_ru',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='parentstoreproduct',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parentstoreproduct',
            name='description_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parentstoreproduct',
            name='hashtags',
            field=models.JSONField(blank=True, default=list, help_text="Ro'yxat, masalan: [#stem, #lego, #6yosh]"),
        ),
        migrations.AddField(
            model_name='parentstoreproduct',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parentstoreproduct',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parentstoreproduct',
            name='short_description_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='parentstoreproduct',
            name='short_description_ru',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='callcenterticket',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_center_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
