from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    SendOTPView, VerifyOTPView, ParentRegisterView, MeView, UpdateLanguageView,
    CreatePairingCodeView, ChildRegisterByCodeView, MyChildrenView, ParentChildLogoutView,
    ParentChildUpdateView,
    SendChildLocationView, SendChildLocationBatchView, ChildLastLocationView, ChildLocationHistoryView,
    DeviceTokenView, DeviceLogoutView,
    ParentRouteListCreateView, ParentRouteDetailView, AssignRouteToChildView,
    ParentChildAssignmentsView, ChildActiveRoutesView, RouteAlertListView,
    SavedLocationListCreateView, SavedLocationDetailView,
    KidsGameCategoryListView, KidsGameListView, KidsGameDetailView,
    KidsShopCategoryListView, KidsShopItemListView, KidsShopItemDetailView,
    KidsWalletView, KidsTransactionListView, KidsShopPurchaseView,
    KidsSOSCreateView, ParentSOSAlertListView, ParentSOSAlertResolveView,
    ChildAppSyncView, ChildAppUsageSyncView, ChildAppPolicyView,
    ParentChildAppListView, ParentSetChildAppLimitView, ParentBlockChildAppView,
    ParentChildAppUsageStatsView,
    AppVersionCheckView, ParentHomeSummaryView, ChildDailyActivitySyncView,
    ChildSavedLocationVisitSyncView,ParentSavedLocationEventListView,ParentChildAppAnalyticsView,
    SubscriptionPlanListView, MySubscriptionView, ActivateSubscriptionView, CancelSubscriptionView,
    ClaimTrialSubscriptionView,
    AdminGiveSubscriptionView, BlogCategoryListView, BlogPostListView, BlogPostDetailView, BlogPostSaveToggleView, BlogPostLikeToggleView,
    ParentStoreCategoryListView, ParentStorePromoBannerListView,
    ParentStoreProductListView, ParentStoreProductDetailView,
    ParentStoreSavedProductListView, ParentStoreSavedProductToggleView,
    ParentStoreOrderListCreateView, ParentStoreOrderDetailView,
    ParentStoreOrderCancelView,
    ChildDailyTrajectoryView,
    ChildFrequentPlacesView,
    ChildFrequentPlaceSaveView,
    ChildFrequentPlaceDismissView,
    ChildDestinationPredictionListView,
    ParentNotificationListView,
    ParentNotificationUnreadCountView,
    ParentNotificationMarkReadView,
    ParentNotificationMarkAllReadView,
    ChildJourneyView,
    ParentMediaUploadView,
    ParentFeatureGatesView,
    AreaBlockRuleListCreateView,
    AreaBlockRuleDetailView,
)


urlpatterns = [
    path("auth/send-otp/", SendOTPView.as_view(), name="send-otp"),
    path("auth/verify-otp/", VerifyOTPView.as_view(), name="verify-otp"),
    path("auth/parent/register/", ParentRegisterView.as_view(), name="parent-register"),
    path("auth/token/refresh/", TokenRefreshView.as_view(), name="token-refresh"),
    path("me/", MeView.as_view(), name="me"),
    path("me/language/", UpdateLanguageView.as_view(), name="update-language"),
    path("version/check/", AppVersionCheckView.as_view(), name="version-check"),
    path("parent/home-summary/", ParentHomeSummaryView.as_view(), name="parent-home-summary"),
    path("parent/pairing-code/", CreatePairingCodeView.as_view(), name="create-pairing-code"),
    path("parent/upload/", ParentMediaUploadView.as_view(), name="parent-media-upload"),
    path("parent/children/", MyChildrenView.as_view(), name="my-children"),
    path("parent/children/<int:child_id>/logout/", ParentChildLogoutView.as_view(), name="parent-child-logout"),
    path("parent/children/<int:child_id>/", ParentChildUpdateView.as_view(), name="parent-child-update"),
    path("child/register-by-code/", ChildRegisterByCodeView.as_view(), name="child-register-by-code"),
    path("child/location/", SendChildLocationView.as_view(), name="send-child-location"),
    path("child/locations/batch/", SendChildLocationBatchView.as_view(), name="send-child-locations-batch"),
    path("child/activity/sync/", ChildDailyActivitySyncView.as_view(), name="child-daily-activity-sync"),
    path("child/saved-location-visit/sync/", ChildSavedLocationVisitSyncView.as_view(), name="child-saved-location-visit-sync"),
    path("parent/children/<int:child_id>/last-location/", ChildLastLocationView.as_view(), name="child-last-location"),
    path("parent/children/<int:child_id>/location-history/", ChildLocationHistoryView.as_view(), name="child-location-history"),
    path("device-token/", DeviceTokenView.as_view(), name="device-token"),
    path("device-token/logout/", DeviceLogoutView.as_view(), name="device-token-logout"),
    path("parent/saved-locations/", SavedLocationListCreateView.as_view(), name="saved-location-list-create"),
    path("parent/saved-locations/<int:location_id>/", SavedLocationDetailView.as_view(), name="saved-location-detail"),
    path("parent/feature-gates/", ParentFeatureGatesView.as_view(), name="parent-feature-gates"),
    path("parent/area-block-rules/", AreaBlockRuleListCreateView.as_view(), name="area-block-rule-list-create"),
    path("parent/area-block-rules/<int:rule_id>/", AreaBlockRuleDetailView.as_view(), name="area-block-rule-detail"),
    path("parent/routes/", ParentRouteListCreateView.as_view(), name="parent-routes"),
    path("parent/routes/<int:route_id>/", ParentRouteDetailView.as_view(), name="parent-route-detail"),
    path("parent/routes/assign/", AssignRouteToChildView.as_view(), name="assign-route-to-child"),
    path("parent/children/<int:child_id>/routes/", ParentChildAssignmentsView.as_view(), name="parent-child-routes"),
    path("child/routes/active/", ChildActiveRoutesView.as_view(), name="child-active-routes"),
    path("parent/route-alerts/", RouteAlertListView.as_view(), name="route-alerts"),
    path("kids/games/categories/", KidsGameCategoryListView.as_view(), name="kids-game-categories"),
    path("kids/games/", KidsGameListView.as_view(), name="kids-games"),
    path("kids/games/<int:game_id>/", KidsGameDetailView.as_view(), name="kids-game-detail"),
    path("kids/shop/categories/", KidsShopCategoryListView.as_view(), name="kids-shop-categories"),
    path("kids/shop/items/", KidsShopItemListView.as_view(), name="kids-shop-items"),
    path("kids/shop/items/<int:item_id>/", KidsShopItemDetailView.as_view(), name="kids-shop-item-detail"),
    path("kids/shop/purchase/", KidsShopPurchaseView.as_view(), name="kids-shop-purchase"),
    path("kids/wallet/", KidsWalletView.as_view(), name="kids-wallet"),
    path("kids/transactions/", KidsTransactionListView.as_view(), name="kids-transactions"),
    path("kids/sos/", KidsSOSCreateView.as_view(), name="kids-sos"),
    path("parent/sos-alerts/", ParentSOSAlertListView.as_view(), name="parent-sos-alerts"),
    path("parent/sos-alerts/<int:sos_id>/resolve/", ParentSOSAlertResolveView.as_view(), name="parent-sos-resolve"),
    path("child/apps/sync/", ChildAppSyncView.as_view(), name="child-app-sync"),
    path("child/apps/usage/sync/", ChildAppUsageSyncView.as_view(), name="child-app-usage-sync"),
    path("child/apps/policies/", ChildAppPolicyView.as_view(), name="child-app-policies"),
    path("parent/children/<int:child_id>/apps/", ParentChildAppListView.as_view(), name="parent-child-apps"),
    path("parent/children/<int:child_id>/apps/usage/", ParentChildAppUsageStatsView.as_view(), name="parent-child-app-usage"),
    path("parent/children/<int:child_id>/apps/<int:app_id>/limit/", ParentSetChildAppLimitView.as_view(), name="parent-child-app-limit"),
    path("parent/children/<int:child_id>/apps/<int:app_id>/block/", ParentBlockChildAppView.as_view(), name="parent-child-app-block"),
    path("parent/saved-location-events/",ParentSavedLocationEventListView.as_view(),name="parent-saved-location-events"),
    path("parent/children/<int:child_id>/apps/analytics/", ParentChildAppAnalyticsView.as_view(), name="parent-child-app-analytics"),
    path("subscription/plans/", SubscriptionPlanListView.as_view(), name="subscription-plans"),
    path("subscription/me/", MySubscriptionView.as_view(), name="my-subscription"),
    path("subscription/activate/", ActivateSubscriptionView.as_view(), name="subscription-activate"),
    path("subscription/trial/claim/", ClaimTrialSubscriptionView.as_view(), name="subscription-trial-claim"),
    path("subscription/cancel/", CancelSubscriptionView.as_view(), name="subscription-cancel"),
    path("admin/subscription/give/", AdminGiveSubscriptionView.as_view(), name="admin-give-subscription"),
    path("blog/categories/", BlogCategoryListView.as_view(), name="blog-categories"),
    path("blog/posts/", BlogPostListView.as_view(), name="blog-posts"),
    path("blog/posts/<int:post_id>/", BlogPostDetailView.as_view(), name="blog-post-detail"),
    path("blog/posts/<int:post_id>/save/", BlogPostSaveToggleView.as_view(), name="blog-post-save-toggle"),
    path("blog/posts/<int:post_id>/like/", BlogPostLikeToggleView.as_view(), name="blog-post-like-toggle"),
    path("parent-store/categories/", ParentStoreCategoryListView.as_view(), name="parent-store-categories"),
    path("parent-store/banners/", ParentStorePromoBannerListView.as_view(), name="parent-store-banners"),
    path("parent-store/products/", ParentStoreProductListView.as_view(), name="parent-store-products"),
    path("parent-store/products/<int:product_id>/", ParentStoreProductDetailView.as_view(), name="parent-store-product-detail"),
    path("parent-store/products/<int:product_id>/save/", ParentStoreSavedProductToggleView.as_view(), name="parent-store-product-save-toggle"),
    path("parent-store/saved/", ParentStoreSavedProductListView.as_view(), name="parent-store-saved"),
    path("parent-store/orders/", ParentStoreOrderListCreateView.as_view(), name="parent-store-orders"),
    path("parent-store/orders/<int:order_id>/", ParentStoreOrderDetailView.as_view(), name="parent-store-order-detail"),
    path("parent-store/orders/<int:order_id>/cancel/", ParentStoreOrderCancelView.as_view(), name="parent-store-order-cancel"),
    path("parent/children/<int:child_id>/trajectory/", ChildDailyTrajectoryView.as_view(), name="child-daily-trajectory"),
    path("parent/children/<int:child_id>/frequent-places/", ChildFrequentPlacesView.as_view(), name="child-frequent-places"),
    path("parent/children/<int:child_id>/frequent-places/<int:place_id>/save/", ChildFrequentPlaceSaveView.as_view(), name="child-frequent-place-save"),
    path("parent/children/<int:child_id>/frequent-places/<int:place_id>/dismiss/", ChildFrequentPlaceDismissView.as_view(), name="child-frequent-place-dismiss"),
    path("parent/children/<int:child_id>/destination-predictions/", ChildDestinationPredictionListView.as_view(), name="child-destination-predictions"),
    path("parent/notifications/", ParentNotificationListView.as_view(), name="parent-notifications"),
    path("parent/notifications/unread-count/", ParentNotificationUnreadCountView.as_view(), name="parent-notifications-unread-count"),
    path("parent/notifications/mark-all-read/", ParentNotificationMarkAllReadView.as_view(), name="parent-notifications-mark-all-read"),
    path("parent/notifications/<int:notification_id>/mark-read/", ParentNotificationMarkReadView.as_view(), name="parent-notification-mark-read"),
    path("parent/children/<int:child_id>/journey/", ChildJourneyView.as_view(), name="child-journey"),
]

# ============================================================================
# Admin panel API
# ============================================================================

from .admin_views import (
    AdminLoginView, AdminMeView, AdminDashboardStatsView,
    AdminBannerListCreate, AdminBannerDetail,
    AdminStoreCategoryListCreate, AdminStoreCategoryDetail,
    AdminStoreProductListCreate, AdminStoreProductDetail,
    AdminBlogCategoryListCreate, AdminBlogCategoryDetail,
    AdminBlogPostListCreate, AdminBlogPostDetail,
    AdminUserListView, AdminUserToggleActiveView,
    AdminSOSAlertListView, AdminBroadcastNotificationView,
    AdminOrderListView, AdminOrderDetailView,
    AdminSubscriptionPlanListCreate, AdminSubscriptionPlanDetail,
    AdminSubscriptionPaymentListView,
    AdminNotificationListView,
    AdminNotificationDetailView,
    AdminBroadcastHistoryView,
    AdminTicketListView, AdminTicketUpdateStatusView,
    AdminLeadBoardView, AdminLeadListCreate, AdminLeadDetailView, AdminLeadCommentsView,
    AdminLeadFullView,
    AdminOperatorListView, AdminOperatorCreateView, AdminOperatorDetailView,
    AdminRoleListCreateView, AdminRoleDetailView,
    AdminAutoTranslateView,
    AdminChangePasswordView,
    AdminChildrenListView,
    AdminMediaUploadView,
    AdminGameCategoryListCreate, AdminGameCategoryDetail,
    AdminGameListCreate, AdminGameDetail,
    AdminSmsTestView,
    AdminNotificationRuleListCreate, AdminNotificationRuleDetail,
    AdminNotificationRuleRunNow, AdminNotificationRuleLogs,
    AdminQuickReplyListCreateView, AdminQuickReplyDetailView,
    TelegramWebhookView,
)

urlpatterns += [
    path("admin/login/", AdminLoginView.as_view(), name="admin-login"),
    path("admin/me/", AdminMeView.as_view(), name="admin-me"),
    path("admin/dashboard/stats/", AdminDashboardStatsView.as_view(), name="admin-dashboard-stats"),
    path("admin/upload/", AdminMediaUploadView.as_view(), name="admin-media-upload"),
    path("admin/sms/test/", AdminSmsTestView.as_view(), name="admin-sms-test"),

    path("admin/notification-rules/", AdminNotificationRuleListCreate.as_view(), name="admin-notif-rule-list"),
    path("admin/notification-rules/<int:rule_id>/", AdminNotificationRuleDetail.as_view(), name="admin-notif-rule-detail"),
    path("admin/notification-rules/<int:rule_id>/run-now/", AdminNotificationRuleRunNow.as_view(), name="admin-notif-rule-run"),
    path("admin/notification-rules/<int:rule_id>/logs/", AdminNotificationRuleLogs.as_view(), name="admin-notif-rule-logs"),

    path("admin/kids/categories/", AdminGameCategoryListCreate.as_view(), name="admin-game-cat-list"),
    path("admin/kids/categories/<int:cat_id>/", AdminGameCategoryDetail.as_view(), name="admin-game-cat-detail"),
    path("admin/kids/games/", AdminGameListCreate.as_view(), name="admin-game-list"),
    path("admin/kids/games/<int:game_id>/", AdminGameDetail.as_view(), name="admin-game-detail"),

    path("admin/banners/", AdminBannerListCreate.as_view(), name="admin-banner-list-create"),
    path("admin/banners/<int:pk>/", AdminBannerDetail.as_view(), name="admin-banner-detail"),

    path("admin/store/categories/", AdminStoreCategoryListCreate.as_view(), name="admin-store-category-list"),
    path("admin/store/categories/<int:pk>/", AdminStoreCategoryDetail.as_view(), name="admin-store-category-detail"),
    path("admin/store/products/", AdminStoreProductListCreate.as_view(), name="admin-store-product-list"),
    path("admin/store/products/<int:pk>/", AdminStoreProductDetail.as_view(), name="admin-store-product-detail"),

    path("admin/blog/categories/", AdminBlogCategoryListCreate.as_view(), name="admin-blog-category-list"),
    path("admin/blog/categories/<int:pk>/", AdminBlogCategoryDetail.as_view(), name="admin-blog-category-detail"),
    path("admin/blog/posts/", AdminBlogPostListCreate.as_view(), name="admin-blog-post-list"),
    path("admin/blog/posts/<int:pk>/", AdminBlogPostDetail.as_view(), name="admin-blog-post-detail"),

    path("admin/users/", AdminUserListView.as_view(), name="admin-user-list"),
    path("admin/users/<int:user_id>/toggle-active/", AdminUserToggleActiveView.as_view(), name="admin-user-toggle-active"),

    path("admin/sos/", AdminSOSAlertListView.as_view(), name="admin-sos-list"),
    path("admin/broadcast/", AdminBroadcastNotificationView.as_view(), name="admin-broadcast"),

    path("admin/orders/", AdminOrderListView.as_view(), name="admin-order-list"),
    path("admin/orders/<int:pk>/", AdminOrderDetailView.as_view(), name="admin-order-detail"),

    path("admin/subscription/plans/", AdminSubscriptionPlanListCreate.as_view(), name="admin-sub-plan-list"),
    path("admin/subscription/plans/<int:pk>/", AdminSubscriptionPlanDetail.as_view(), name="admin-sub-plan-detail"),
    path("admin/subscription/payments/", AdminSubscriptionPaymentListView.as_view(), name="admin-sub-payment-list"),

    path("admin/notifications/", AdminNotificationListView.as_view(), name="admin-notif-list"),
    path("admin/notifications/<int:notif_id>/", AdminNotificationDetailView.as_view(), name="admin-notif-detail"),
    path("admin/broadcast/history/", AdminBroadcastHistoryView.as_view(), name="admin-broadcast-history"),

    path("admin/tickets/", AdminTicketListView.as_view(), name="admin-ticket-list"),
    path("admin/tickets/<int:ticket_id>/status/", AdminTicketUpdateStatusView.as_view(), name="admin-ticket-status"),
    path("admin/leads/board/", AdminLeadBoardView.as_view(), name="admin-lead-board"),
    path("admin/leads/", AdminLeadListCreate.as_view(), name="admin-lead-create"),
    path("admin/leads/<int:ticket_id>/", AdminLeadDetailView.as_view(), name="admin-lead-detail"),
    path("admin/leads/<int:ticket_id>/full/", AdminLeadFullView.as_view(), name="admin-lead-full"),
    path("admin/leads/<int:ticket_id>/comments/", AdminLeadCommentsView.as_view(), name="admin-lead-comments"),

    path("admin/support/quick-replies/", AdminQuickReplyListCreateView.as_view(), name="admin-quick-reply-list"),
    path("admin/support/quick-replies/<int:qr_id>/", AdminQuickReplyDetailView.as_view(), name="admin-quick-reply-detail"),

    path("admin/operators/", AdminOperatorListView.as_view(), name="admin-operator-list"),
    path("admin/operators/create/", AdminOperatorCreateView.as_view(), name="admin-operator-create"),
    path("admin/operators/<int:user_id>/", AdminOperatorDetailView.as_view(), name="admin-operator-detail"),
    path("admin/roles/", AdminRoleListCreateView.as_view(), name="admin-role-list-create"),
    path("admin/roles/<int:role_id>/", AdminRoleDetailView.as_view(), name="admin-role-detail"),
    path("admin/translate/", AdminAutoTranslateView.as_view(), name="admin-translate"),

    path("admin/change-password/", AdminChangePasswordView.as_view(), name="admin-change-password"),
    path("admin/children/", AdminChildrenListView.as_view(), name="admin-children-list"),
    path("telegram/webhook/", TelegramWebhookView.as_view()),
]