# Generated by Django 5.2.14 on 2026-06-10 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jojolingo', '0002_placementquestion_placementansweroption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMethodRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistake_type', models.CharField(max_length=100)),
                ('level_code', models.CharField(default='A0', max_length=10)),
                ('recommended_method', models.CharField(choices=[('repeat', 'Repeat'), ('visual', 'Visual'), ('example', 'Example'), ('dialogue', 'Dialogue'), ('game', 'Game'), ('review', 'Review')], max_length=30)),
                ('message_uz', models.TextField()),
                ('message_ru', models.TextField(blank=True, default='')),
                ('message_en', models.TextField(blank=True, default='')),
                ('message_kk', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('explanation_uz', models.TextField(blank=True, default='')),
                ('explanation_ru', models.TextField(blank=True, default='')),
                ('explanation_en', models.TextField(blank=True, default='')),
                ('explanation_kk', models.TextField(blank=True, default='')),
                ('level_code', models.CharField(choices=[('A0', 'A0 - Starter'), ('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate')], default='A0', max_length=10)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_rules', to='jojolingo.learningcourse')),
            ],
            options={
                'ordering': ['level_code', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150)),
                ('translation_uz', models.CharField(blank=True, default='', max_length=150)),
                ('translation_ru', models.CharField(blank=True, default='', max_length=150)),
                ('translation_en', models.CharField(blank=True, default='', max_length=150)),
                ('translation_kk', models.CharField(blank=True, default='', max_length=150)),
                ('level_code', models.CharField(choices=[('A0', 'A0 - Starter'), ('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate')], default='A0', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jojolingo/vocabulary/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='jojolingo/vocabulary/audio/')),
                ('usage_example', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_items', to='jojolingo.language')),
            ],
            options={
                'ordering': ['level_code', 'order', 'id'],
            },
        ),
    ]
