# Generated by Django 5.2.14 on 2026-06-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jojolingo', '0003_learningmethodrule_grammarrule_vocabularyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='accepted_answers',
            field=models.JSONField(blank=True, default=list, help_text="Alternative correct answers, masalan: ['hi', 'hello']"),
        ),
    ]
