# Generated by Django 5.2.14 on 2026-06-10 10:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jojolingo', '0005_wordprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name_uz', models.CharField(max_length=64)),
                ('name_ru', models.CharField(blank=True, max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64)),
                ('name_kk', models.CharField(blank=True, max_length=64)),
                ('avatar', models.CharField(max_length=64)),
                ('personality', models.CharField(default='cheerful', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('complete_lessons', 'N ta dars tugat'), ('review_words', "N ta so'zni takrorla"), ('earn_xp', "N XP yig'"), ('perfect_exercises', 'N ta mashqni xatosiz bajar')], max_length=32)),
                ('target_value', models.PositiveIntegerField()),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('title_uz', models.CharField(max_length=120)),
                ('title_ru', models.CharField(blank=True, max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('title_kk', models.CharField(blank=True, max_length=120)),
                ('min_level', models.CharField(blank=True, max_length=8)),
                ('max_level', models.CharField(blank=True, max_length=8)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('condition_type', models.CharField(choices=[('lessons_completed', 'Tugatilgan darslar soni'), ('xp_total', 'Jami XP'), ('streak_days', 'Streak kunlari'), ('words_mastered', "O'zlashtirilgan so'zlar"), ('perfect_lessons', 'Xatosiz darslar'), ('placement_done', 'Placement test tugatildi'), ('course_completed', 'Kurs tugatildi'), ('first_lesson', 'Birinchi dars')], max_length=32)),
                ('threshold', models.PositiveIntegerField(default=1)),
                ('title_uz', models.CharField(max_length=120)),
                ('title_ru', models.CharField(blank=True, max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('title_kk', models.CharField(blank=True, max_length=120)),
                ('description_uz', models.CharField(blank=True, max_length=255)),
                ('description_ru', models.CharField(blank=True, max_length=255)),
                ('description_en', models.CharField(blank=True, max_length=255)),
                ('description_kk', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'threshold'],
                'indexes': [models.Index(fields=['condition_type', 'is_active'], name='jojolingo_a_conditi_a48176_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChildCompanionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Xursand'), ('excited', 'Hayajonda'), ('sleepy', 'Uyqusiragan'), ('worried', 'Xavotirda'), ('proud', 'Faxrlanmoqda')], default='happy', max_length=16)),
                ('friendship_xp', models.PositiveIntegerField(default=0)),
                ('friendship_level', models.PositiveIntegerField(default=1)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jojolingo.aicompanion')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companion_state', to='jojolingo.childlearningprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ChildAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jojolingo.achievement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='jojolingo.childlearningprofile')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('profile', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='CompanionMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('daily_greeting', 'Kunlik salomlashish'), ('lesson_complete', 'Dars tugadi'), ('perfect_lesson', 'Xatosiz dars'), ('mistake', 'Xato qilindi'), ('streak_milestone', 'Streak bosqichi'), ('streak_danger', 'Streak yonish arafasida'), ('achievement', 'Achievement olindi'), ('comeback', 'Uzoq tanaffusdan qaytdi'), ('daily_tasks_done', 'Kunlik tasklar tugadi')], max_length=32)),
                ('text_uz', models.CharField(max_length=255)),
                ('text_ru', models.CharField(blank=True, max_length=255)),
                ('text_en', models.CharField(blank=True, max_length=255)),
                ('text_kk', models.CharField(blank=True, max_length=255)),
                ('mood_after', models.CharField(choices=[('happy', 'Xursand'), ('excited', 'Hayajonda'), ('sleepy', 'Uyqusiragan'), ('worried', 'Xavotirda'), ('proud', 'Faxrlanmoqda')], default='happy', max_length=16)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('companion', models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — barcha personajlar uchun umumiy", null=True, on_delete=django.db.models.deletion.CASCADE, to='jojolingo.aicompanion')),
            ],
            options={
                'indexes': [models.Index(fields=['trigger', 'is_active'], name='jojolingo_c_trigger_c63723_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChildDailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('target', models.PositiveIntegerField()),
                ('xp_reward', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='jojolingo.childlearningprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jojolingo.dailytasktemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'date'], name='jojolingo_c_profile_f9e3cc_idx')],
                'unique_together': {('profile', 'template', 'date')},
            },
        ),
    ]
