# Generated by Django 5.2.14 on 2026-06-10 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jojolingo', '0006_aicompanion_dailytasktemplate_achievement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('exercises_answered', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('words_reviewed', models.PositiveIntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='jojolingo.childlearningprofile')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['profile', 'date'], name='jojolingo_c_profile_698c46_idx')],
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
