# Generated by Django 5.2.14 on 2026-06-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jojolingo', '0007_childdailyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
