# Generated by Django 5.2.14 on 2026-06-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jojolingo', '0008_exercise_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='childlearningprofile',
            name='completed_lessons_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childlearningprofile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childlearningprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='childlearningprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childlearningprofile',
            name='last_recommended_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='childlearningprofile',
            name='learning_speed',
            field=models.CharField(choices=[('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='childlearningprofile',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childlearningprofile',
            name='mastered_words_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childlearningprofile',
            name='perfect_lessons_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childlearningprofile',
            name='streak_freeze_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childlearningprofile',
            name='strong_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='childlearningprofile',
            name='weak_topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
