# Generated by Django 5.2.14 on 2026-06-12 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jojolingo', '0009_childlearningprofile_completed_lessons_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('challenge_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('special', 'Special')], max_length=20)),
                ('target_type', models.CharField(choices=[('xp', 'XP'), ('lesson', 'Lesson'), ('word', 'Word'), ('streak', 'Streak')], max_length=20)),
                ('target_value', models.PositiveIntegerField(default=1)),
                ('reward_xp', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(blank=True, default='', max_length=100)),
                ('name_ru', models.CharField(blank=True, default='', max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
                ('name_kk', models.CharField(blank=True, default='', max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='jojolingo/topics/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='aicompanion',
            name='level',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChildLearningAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_accuracy', models.FloatField(default=0)),
                ('average_time_per_exercise', models.FloatField(default=0)),
                ('total_exercises', models.PositiveIntegerField(default=0)),
                ('total_correct_answers', models.PositiveIntegerField(default=0)),
                ('total_wrong_answers', models.PositiveIntegerField(default=0)),
                ('visual_score', models.PositiveIntegerField(default=0)),
                ('dialogue_score', models.PositiveIntegerField(default=0)),
                ('repeat_score', models.PositiveIntegerField(default=0)),
                ('game_score', models.PositiveIntegerField(default=0)),
                ('learning_speed_score', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='topics',
            field=models.ManyToManyField(blank=True, to='jojolingo.topic'),
        ),
        migrations.CreateModel(
            name='ChildChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_challenges', to='jojolingo.challenge')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('child', 'challenge')},
            },
        ),
    ]
