# Generated by Django 5.2.14 on 2026-06-12 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jojolingo', '0010_challenge_topic_aicompanion_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildTopicStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interactions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_stats', to='jojolingo.childlearningprofile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jojolingo.topic')),
            ],
            options={
                'unique_together': {('profile', 'topic')},
            },
        ),
    ]
